### ISSUE TITLE
CompressionKind Issue

### ISSUE THREAD

**Issue by maranmani978** [noirello/pyorc#2]
When I try to change CompressionKind from ZLIB to SNAPPY

import pyorc

tuples = (1, "hii")
with open("/path/toOrcFile", "wb") as writeData:
    with pyorc.Writer(writeData, schema, compression=pyorc.CompressionKind.SNAPPY) as orcWriter:
        orcWriter.write(tuples)

It throws error as:
File "/PycharmProjects/orcWriter/venv/lib/python3.7/site-packages/pyorc/writer.py", line 59, in __init__
    conv,
RuntimeError: compression codec

**Comment by noirello** [comment]
This was a suppress to me as well (because only tested manually with CompressionKind.ZSTD and CompressionKind.None), but it seems the core C++ ORC lib [does not support](https://github.com/apache/orc/blob/028261ad6e26d8ae9f9483c8aeb76a85c7f1168b/c%2B%2B/src/Compression.cc#L1121) SNAPPY (or LZ4 or LZO) for its writer.

These enums should be remove until the compression methods are implemented in the core lib.

**Comment by jfmontanaro** [comment]
It looks like Snappy support has now been added to the C++ lib (in fact, it looks like you added it yourself) but I can't seem to make it work. I tried updating the ORC version in setup.py to 1.6.9, then building and installing, but I still get `RuntimeError: compression codec` when I try to create a `Writer` with Snappy compression.

Any quick fixes I might be able to try out? Or are we still waiting on upstream to fully implement support for this?

**Comment by noirello** [comment]
You need to use the ORC main branch for that feature. I think it will be released in 1.7.0.

**Comment by jfmontanaro** [comment]
Thanks! That does allow writing with Snappy compression.

Unfortunately it seems that the C++ version of the lib just writes less space-efficient ORC files than the Java version, by a significant margin. Oh well.

**Comment by zenkovac** [comment]
@jfmontanaro  using pyroc parameter in the writer dict_key_size_threshold=1.0 yields very small files equal to java compression in size
