### ISSUE TITLE
predicate to skip rows doesn't seem to work for timestamps

### ISSUE THREAD

**Issue by robrice** [noirello/pyorc#48]
I have a script with a predicate I would like to use to skip rows that have a timestamp <= some value - but - it does not seem to skip:

Here is a excerpt of my code snipette:

    ttime = datetime.datetime.strptime('2021-12-08 00:00:00 +00:00','%Y-%m-%d %H:%M:%S %z')
    pred = pyorc.PredicateColumn(pyorc.TypeKind.TIMESTAMP, name="timestamp") > ttime
    reader = pyorc.Reader(data,predicate=pred)

Resulting rows don't seem to skip anything at all.

**Comment by noirello** [comment]
What's the size of the `row_index_stride` of your file? What's the min and max value of the `timestamp` column?

**Comment by robrice** [comment]
I'm actually opening the OSM (Open Steet Map) planet data hosted publicly on AWS:
 orc_file = "s3://osm-pds/planet/planet-latest.orc"

As a newbie, I'm not sure how to determine the row.index.stride, however, here is some code and the schema:

Schema:   struct<id:bigint,type:string,tags:map<string,string>,lat:decimal(9,7),lon:decimal(10,7),nds:array<struct<ref:bigint>>,members:array<struct<type:string,ref:bigint,role:string>>,changeset:bigint,timestamp:timestamp,uid:bigint,user:string,version:bigint,visible:boolean>
Stripes:  3091
Rows:     8237861440
Lengths:  {'content_length': 88430475540, 'file_footer_length': 47470, 'file_postscript_length': 27, 'file_length': 88431268984, 'stripe_statistics_length': 745946}
Stripes   3091
Stripe Len  3091

The above info was generated with:
            print("Schema:  ", reader.schema)
            print("Stripes: ", reader.num_of_stripes)
            print("Rows:    ", len(reader))
            print("Lengths: ", reader.bytes_lengths)
            print("Stripes  ", reader.num_of_stripes)
            print("Stripe Len ", reader.num_of_stripes)

The manner I read the file with the predicate is as follows:

        ttime = datetime.datetime.strptime('2021-12-08 00:00:00 +00:00','%Y-%m-%d %H:%M:%S %z')
        pred = pyorc.PredicateColumn(pyorc.TypeKind.TIMESTAMP, name="timestamp") > ttime
        print("Opening ORC Source: ",orc_file)
        with smart_open(orc_file,"rb") as data:
            print("Reading ORC data")
            reader = pyorc.Reader(data,batch_size=rows_to_read,predicate=pred)

**Comment by robrice** [comment]
I should add that after this code:
  for stripe in range (0,numstripes+1):

                # Read next stripe
                print("Reading stripe {}".format(stripe))
                stripe_data = reader.read_stripe(stripe)
                print("Length: {} row offset {}".format(len(stripe_data),stripe_data.row_offset))

**After reaading stripe 0:**
Reading stripe 0
Length: 2350080 row offset 0
Seeking to 2115072
Stripe:0 Stipelen:2350080 Rec:70001 Rec[0]:1 Rec[end]:23332452 Nwrite:0 Wwrite:0 Typeo:0 NegWay:0, Outside:0 Ntime:0
Reading stripe 1
Length: 2283520 row offset 2350080

**Comment by noirello** [comment]
Indeed, the predicates works quite oddly with this data.

My first thought was that because the data is not ordered by the "timestamp" column, each row group could contain records with greater timestamp, than `2021-12-08 00:00:00 +00:00`, thus cannot skip anything.

But it works weird with the "id" column as well (which is clearly ordered).

```
>>> data = open("./planet-latest.orc", "rb")
>>> r = pyorc.Reader(data)
>>> r.row_index_stride
10000
>>> r = pyorc.Reader(data, predicate=(pyorc.PredicateColumn(pyorc.TypeKind.LONG, "id") > 20000))
>>> next(r)
(1, 'node', {'communication:microwave': 'yes', 'communication:radio': 'fm', 'man_made': 'mast', 'name': 'Monte Piselli - San Giacomo', 'description': 'Radio Subasio', 'tower:construction': 'lattice', 'frequency': '105.5 MHz', 'tower:type': 'communication'}, Decimal('42.7957187'), Decimal('13.5690032'), [], [], 115176312, datetime.datetime(2021, 12, 20, 17, 54, 50, tzinfo=zoneinfo.ZoneInfo(key='UTC')), 9475258, 'Aranc', 27, True)
>>> r = pyorc.Reader(data, predicate=(pyorc.PredicateColumn(pyorc.TypeKind.LONG, "id") > 120000))
>>> next(r)
(115772, 'node', {}, Decimal('55.7485702'), Decimal('9.1380955'), [], [], 75855309, datetime.datetime(2019, 10, 17, 17, 24, 56, tzinfo=zoneinfo.ZoneInfo(key='UTC')), 2677992, 'mikkolukas', 12, True)
```
The `row_index_stride` which gives the size of the row group is 10000, but have to use a much larger id value (120000) to actually skip any records.

Unfortunately, I cannot give you any reasonable explanation what's happening here. It looks like that my understanding of ORC's predicates/search arguments is also fairly insufficient. I'll try to look into it in more details as soon as I can.

**Comment by robrice** [comment]
Thanks tons for doing that! It would be great to be able to apply a filter - that OSM Planet table is HUGE.

**Comment by noirello** [comment]
Actually, the predicates just work fine. I just wasn't paying attention enough.

The id of the 10000th element (which is last item in the first row group) in the dataset is: 115771.
So in my previous example, where the predicate that compares the "id" column to greater than 20000 should rightfully include the first row group and therefore the first item in the dataset. 

```
>>> r = pyorc.Reader(data, predicate=(pyorc.PredicateColumn(pyorc.TypeKind.LONG, "id") > 20000))
>>> next(r)
(1, 'node', {'communication:microwave': 'yes', 'communication:radio': 'fm', 'man_made': 'mast', 'name': 'Monte Piselli - San Giacomo', 'description': 'Radio Subasio', 'tower:construction': 'lattice', 'frequency': '105.5 MHz', 'tower:type': 'communication'}, Decimal('42.7957187'), Decimal('13.5690032'), [], [], 115176312, datetime.datetime(2021, 12, 20, 17, 54, 50, tzinfo=zoneinfo.ZoneInfo(key='UTC')), 9475258, 'Aranc', 27, True)
```

Using your original predicate also exclude some records from the dataset, although probably far less then you'd expect, because the data is not ordered by the "timestamp" column. Here's how you can check it for the first stripe:

```
>>> ttime = datetime.datetime.strptime('2021-12-08 00:00:00 +00:00','%Y-%m-%d %H:%M:%S %z')
>>> pred = pyorc.PredicateColumn(pyorc.TypeKind.TIMESTAMP, name="timestamp") > ttime
>>> reader = pyorc.Reader(data, predicate=pred)
>>> stripe = reader.read_stripe(0)
>>> len(stripe)
2350080  # This is the number of records read from the stripe's footer
>>> len(list(stripe))
2080000  # And this is the actual record number read from the stripe
``` 

I think `pyorc` is not the right tool for your task, or at least not on its own. To efficiently filter this 80GB+ ORC file will require using some query engine (for example Spark, Presto/Trino, or Hive) that's optimised for this kind of work.
