### ISSUE TITLE
Documentation for making a schema programmatically

### ISSUE THREAD

**Issue by warmwaffles** [noirello/pyorc#8]
It would be great if there was more documentation around building the schema programmatically. 

Right now I am feeling my way through the repl and c++ source and python to figure out how to do it.

**Comment by noirello** [comment]
I'm actually trying to reimplement the TypeDescription in Python, because I wasn't satisfied with the current solution. It's still in development on [this branch](https://github.com/noirello/pyorc/tree/experiment/description), but basically you can use Python objects to create a schema:

```python3
>>> schema = Struct(ts=Timestamp(), number=BigInt(), hmap=Map(key=String(),value=Double()))
>>> str(schema)
'struct<ts:timestamp,number:bigint,hmap:map<string,double>>'
```

If you have some thoughts about it, I'd like to hear them.

**Comment by warmwaffles** [comment]
I like that approach to be honest. The way I was doing it was like this.

```python
    schema = typedescription(TypeKind.STRUCT)
    schema.add_field("datetime", typedescription(TypeKind.TIMESTAMP))
    schema.add_field("open", typedescription(TypeKind.DECIMAL))
    schema.add_field("close", typedescription(TypeKind.DECIMAL))
    schema.add_field("low", typedescription(TypeKind.DECIMAL))
    schema.add_field("high", typedescription(TypeKind.DECIMAL))
    schema.add_field("volume", typedescription(TypeKind.LONG))
```

But your way seems so much better.
